force-app/main/default/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/objects/Conversation_Note__c/fields/CRM_Henvendelse_BehandlingskjedeId__c.field-meta.xml
<CustomField>
    <fullName>CRM_Henvendelse_BehandlingskjedeId__c</fullName>
    <externalId>true</externalId>
    <label>Henvendelse BehandlingskjedeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_ConvNoteReferenceHandler.cls
public without sharing class CRM_ConvNoteReferenceHandler extends MyTriggers {
    public override void onBeforeInsert() {
        for (Conversation_Note__c convNote : (List<Conversation_Note__c>) Records) {
            String apiRef = CRM_ReferenceUtil.generateReference(convNote);
            convNote.CRM_API_Reference__c = apiRef;
            if (String.isBlank(convNote.CRM_Henvendelse_BehandlingskjedeId__c)) {
                //If the CRM_Henvendelse_BehandlingskjedeId__c is not blank this is created as a follow up conv note on the same chain, else populate with its own ref
                convNote.CRM_Henvendelse_BehandlingskjedeId__c = apiRef;
            }
        }
    }
}