force-app/main/default/objects/Conversation_Note__c/Conversation_Note__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing conversation notes from i.e. inbound calls</description>
    <label>Conversation Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Conversation Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/objects/Conversation_Note__c/fields/CRM_Henvendelse_BehandlingskjedeId__c.field-meta.xml
<CustomField>
    <fullName>CRM_Henvendelse_BehandlingskjedeId__c</fullName>
    <externalId>true</externalId>
    <label>Henvendelse BehandlingskjedeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_ConvNoteReferenceHandler_Test.cls
@isTest
public class CRM_ConvNoteReferenceHandler_Test {
    @isTest
    static void testReferenceGeneration() {
        Test.startTest();
        CRM_HENV_Base_TestDataFactory.createRecord(new Conversation_Note__c());
        Test.stopTest();

        System.assertEquals(
            1,
            [
                SELECT COUNT()
                FROM Conversation_Note__c
                WHERE CRM_API_Reference__c != NULL AND CRM_Henvendelse_BehandlingskjedeId__c != NULL
            ]
        );
    }

    @isTest
    static void testChainIdPersistence() {
        Test.startTest();
        CRM_HENV_Base_TestDataFactory.createRecord(
            new Conversation_Note__c(CRM_Henvendelse_BehandlingskjedeId__c = '123TEST')
        );
        Test.stopTest();

        System.assertEquals(
            1,
            [
                SELECT COUNT()
                FROM Conversation_Note__c
                WHERE CRM_API_Reference__c != NULL AND CRM_Henvendelse_BehandlingskjedeId__c = '123TEST'
            ]
        );
    }
}