force-app/main/default/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_Latest_Message_Datetime__c.field-meta.xml
<CustomField>
    <fullName>CRM_Latest_Message_Datetime__c</fullName>
    <label>Latest Message Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/UpdateThreadSummaryBatch.cls
public class UpdateThreadSummaryBatch implements Database.Batchable<Thread__c>{

    public final String query;

    public UpdateThreadSummaryBatch() {
        query = 'SELECT Id FROM Thread__c WHERE CRM_Latest_Message_Datetime__c = LAST_N_DAYS:90 OR CRM_Latest_Message_Datetime__c = TODAY';
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Thread__c> scope){
        for(Thread__c thread : scope){
            Map<String,Object> flowVars = new Map<String, Object>();
            flowVars.put('threadId', thread.Id);
            Flow.Interview.CRMHenvendelse_Thread_Subflow_RecalculateMessageSummary flow = new Flow.Interview.CRMHenvendelse_Thread_Subflow_RecalculateMessageSummary(flowVars);
            flow.start();
        }
    }

    public void finish(Database.BatchableContext BC){}
}