force-app/main/default/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/core-functionality/objects/Thread__c/fields/CRM_Thread_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Thread_Type__c</fullName>
    <label>Thread Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFAULT</fullName>
                <default>true</default>
                <label>DEFAULT</label>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>STB</fullName>
            </value>
            <value>
                <fullName>CHAT</fullName>
            </value>
            <value>
                <fullName>AAREG_EXP</fullName>
            </value>
            <value>
                <fullName>AAREG_INT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thread__c/fields/CRM_Type__c.field-meta.xml
<CustomField>
    <fullName>CRM_Type__c</fullName>
    <externalId>true</externalId>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_ThreadDefaultAtomationTest.cls
@isTest
public without sharing class CRM_ThreadDefaultAtomationTest {
    @isTest
    static void typeFieldSetOnBeforeInsert() {
        Thread__c thread = new Thread__c(CRM_Thread_Type__c = 'DEFAULT');

        Test.startTest();
        insert thread;
        Test.stopTest();

        Thread__c updatedThread = [
            SELECT Id, CRM_Thread_Type__c, CRM_Type__c
            FROM Thread__c
            WHERE Id = :thread.Id
        ];
        System.assertEquals(updatedThread.CRM_Thread_Type__c, updatedThread.CRM_Type__c, 'Could not set TYpe equal to Thread Type');
        System.assertEquals('DEFAULT', updatedThread.CRM_Type__c, 'Could not set Type correctly');
    }
    
}