force-app/main/default/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <description>Represents a messaging thread</description>
    <label>Thread</label>
    <nameField>
        <label>Thread Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/CRM_API_Reference__c.field-meta.xml
<CustomField>
    <fullName>CRM_API_Reference__c</fullName>
    <description>Record reference that is exposed via API</description>
    <externalId>true</externalId>
    <label>API Reference</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/core-functionality/classes/CRM_ApiReferenceBatcher_Test.cls
@isTest
public class CRM_ApiReferenceBatcher_Test {

    @isTest
    static void testThreadRefSwitch() {
        String query = 'SELECT Id, CRM_API_Reference__c, CRM_Henvendelse_BehandlingsId__c FROM Thread__c';
        CRM_ApiReferenceBatcher batcher = new CRM_ApiReferenceBatcher(true, query);

        Test.startTest();
        Database.executeBatch(batcher);
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM Thread__c WHERE CRM_API_Reference__c = '123TEST']);
    }
}